version: '3'

services:
  nginx:
    build: ./docker/nginx
    container_name: web
    ports:
      - "8088:80"
    volumes:
      - ./symfony_demo:/var/www/
      - ./docker/nginx/sites/:/etc/nginx/sites-available
    links:
      - php
    depends_on:
      - php

  php:
    build: ./docker/php
    container_name: app
    expose:
      - "9000"
      - "9001"
    volumes:
      - ./symfony_demo:/var/www
      - var:/var/www/var
    links:
      - mysql
      - redis
      - es01
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8
    container_name: db
    command: mysqld --default-authentication-plugin=mysql_native_password --sql_mode=""
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "33060:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=${DATABASE_NAME}

  redis:
    image: redis:6-alpine
    container_name: cache
    ports:
      - "6379:6379"

volumes:
  var:
    driver: local
  dbdata:
    driver: local

networks:
  default:
    driver: bridge
